language: node_js
sudo: false
dist: trusty
node_js: stable
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
    - node_modules
script:
  - xvfb-run wct --npm --configFile wct-travis.conf.json
  - npm run lint
