language: node_js
sudo: false
dist: trusty
node_js: stable
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - node_modules
before_script:
- npm run build
script:
- xvfb-run wct --npm
