language: node_js
sudo: false
dist: trusty
node_js: stable
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
    - node_modules
script:
  # Sadly there are issues when using Chrome on travis (Polymer/web-component-tester#656)
  - xvfb-run wct --npm -l firefox
  - npm run lint
